source ''

gem 'chef', '~> 11.16.4'

group :unit do
  gem 'chefspec'
  gem 'rspec'
  gem 'serverspec'
end

group :style do
  gem 'foodcritic'
  gem 'rubocop'
end

group :development do
  gem 'berkshelf'
  gem 'rake'
  gem 'guard'
  gem 'guard-rake'
  gem 'chef-rewind'
  gem 'simple-graphite'
end

group :integration do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'kitchen-openstack'
  gem 'kitchen-ec2', '0.9.5'
end
